import { Injectable } from '@angular/core';
import { Game } from '../model/game';

@Injectable({
  providedIn: 'root'
})
export class GameService {
  private games = new Array<Game>();
  private autoGeneratedId = 0;

  constructor() {
  }

  insert(game: Game): void {
    if (isNaN(this.autoGeneratedId)) { this.autoGeneratedId = 1; }
    game.id = this.autoGeneratedId++;
    this.games.push(game);
    this.save();
  }

  list(): Array<Game> {
    this.load();
    return this.games;
  }

  remove(id: number): void {
    this.games = this.games.filter((game) => game.id !== id );
    this.save();
  }

  update(game: Game): void {
    const i = this.games.findIndex((el) => el.id === game.id);
    if (i >= 0) { this.games[i] = game; }

    this.save();
  }

  save(): void {
    localStorage.setItem('autoGeneratedId', this.autoGeneratedId.toString());
    const gamesJson = JSON.stringify(this.games);
    localStorage.setItem('games', gamesJson);
  }

  load(): void {
    const autoGenId = localStorage.getItem('autoGeneratedId');

    if (autoGenId) { this.autoGeneratedId = Number(autoGenId); }

    const gamesJson = localStorage.getItem('games');

    if (gamesJson) { this.games = JSON.parse(gamesJson); }
  }
}
